module Champion
  extend ActiveSupport::Concern

  # Current as of Patch 5.16.1
  CHAMPIONS = {
    "35" => {"name" => "Shaco", "image" => "Shaco.png"},
    "36" => {"name" => "Dr. Mundo", "image" => "DrMundo.png"},
    "33" => {"name" => "Rammus", "image" => "Rammus.png"},
    "34" => {"name" => "Anivia", "image" => "Anivia.png"},
    "39" => {"name" => "Irelia", "image" => "Irelia.png"},
    "157" => {"name" => "Yasuo", "image" => "Yasuo.png"},
    "37" => {"name" => "Sona", "image" => "Sona.png"},
    "38" => {"name" => "Kassadin", "image" => "Kassadin.png"},
    "154" => {"name" => "Zac", "image" => "Zac.png"},
    "150" => {"name" => "Gnar", "image" => "Gnar.png"},
    "43" => {"name" => "Karma", "image" => "Karma.png"},
    "42" => {"name" => "Corki", "image" => "Corki.png"},
    "41" => {"name" => "Gangplank", "image" => "Gangplank.png"},
    "40" => {"name" => "Janna", "image" => "Janna.png"},
    "201" => {"name" => "Braum", "image" => "Braum.png"},
    "22" => {"name" => "Ashe", "image" => "Ashe.png"},
    "23" => {"name" => "Tryndamere", "image" => "Tryndamere.png"},
    "24" => {"name" => "Jax", "image" => "Jax.png"},
    "25" => {"name" => "Morgana", "image" => "Morgana.png"},
    "26" => {"name" => "Zilean", "image" => "Zilean.png"},
    "27" => {"name" => "Singed", "image" => "Singed.png"},
    "28" => {"name" => "Evelynn", "image" => "Evelynn.png"},
    "29" => {"name" => "Twitch", "image" => "Twitch.png"},
    "3" => {"name" => "Galio", "image" => "Galio.png"},
    "161" => {"name" => "Vel'Koz", "image" => "Velkoz.png"},
    "2" => {"name" => "Olaf", "image" => "Olaf.png"},
    "1" => {"name" => "Annie", "image" => "Annie.png"},
    "7" => {"name" => "LeBlanc", "image" => "Leblanc.png"},
    "30" => {"name" => "Karthus", "image" => "Karthus.png"},
    "6" => {"name" => "Urgot", "image" => "Urgot.png"},
    "32" => {"name" => "Amumu", "image" => "Amumu.png"},
    "5" => {"name" => "Xin Zhao", "image" => "XinZhao.png"},
    "31" => {"name" => "Cho'gath", "image" => "Chogath.png"},
    "4" => {"name" => "Twisted Fate", "image" => "TwistedFate.png"},
    "9" => {"name" => "Fiddlesticks", "image" => "FiddleSticks.png"},
    "8" => {"name" => "Vladimir", "image" => "Vladimir.png"},
    "19" => {"name" => "Warwick", "image" => "Warwick.png"},
    "17" => {"name" => "Teemo", "image" => "Teemo.png"},
    "18" => {"name" => "Tristana", "image" => "Tristana.png"},
    "15" => {"name" => "Sivir", "image" => "Sivir.png"},
    "16" => {"name" => "Soraka", "image" => "Soraka.png"},
    "13" => {"name" => "Ryze", "image" => "Ryze.png"},
    "14" => {"name" => "Sion", "image" => "Sion.png"},
    "11" => {"name" => "Master Yi", "image" => "MasterYi.png"},
    "12" => {"name" => "Alistar", "image" => "Alistar.png"},
    "21" => {"name" => "Miss Fortune", "image" => "MissFortune.png"},
    "20" => {"name" => "Nunu", "image" => "Nunu.png"},
    "107" => {"name" => "Rengar", "image" => "Rengar.png"},
    "106" => {"name" => "Volibear", "image" => "Volibear.png"},
    "105" => {"name" => "Fizz", "image" => "Fizz.png"},
    "104" => {"name" => "Graves", "image" => "Graves.png"},
    "103" => {"name" => "Ahri", "image" => "Ahri.png"},
    "99" => {"name" => "Lux", "image" => "Lux.png"},
    "102" => {"name" => "Shyvana", "image" => "Shyvana.png"},
    "101" => {"name" => "Xerath", "image" => "Xerath.png"},
    "412" => {"name" => "Thresh", "image" => "Thresh.png"},
    "98" => {"name" => "Shen", "image" => "Shen.png"},
    "222" => {"name" => "Jinx", "image" => "Jinx.png"},
    "96" => {"name" => "Kog'Maw", "image" => "KogMaw.png"},
    "223" => {"name" => "Tahm Kench", "image" => "TahmKench.png"},
    "92" => {"name" => "Riven", "image" => "Riven.png"},
    "91" => {"name" => "Talon", "image" => "Talon.png"},
    "90" => {"name" => "Malzahar", "image" => "Malzahar.png"},
    "429" => {"name" => "Kalista", "image" => "Kalista.png"},
    "10" => {"name" => "Kayle", "image" => "Kayle.png"},
    "421" => {"name" => "Rek'Sai", "image" => "RekSai.png"},
    "89" => {"name" => "Leona", "image" => "Leona.png"},
    "79" => {"name" => "Gragas", "image" => "Gragas.png"},
    "117" => {"name" => "Lulu", "image" => "Lulu.png"},
    "114" => {"name" => "Fiora", "image" => "Fiora.png"},
    "78" => {"name" => "Poppy", "image" => "Poppy.png"},
    "115" => {"name" => "Ziggs", "image" => "Ziggs.png"},
    "77" => {"name" => "Udyr", "image" => "Udyr.png"},
    "112" => {"name" => "Viktor", "image" => "Viktor.png"},
    "113" => {"name" => "Sejuani", "image" => "Sejuani.png"},
    "110" => {"name" => "Varus", "image" => "Varus.png"},
    "111" => {"name" => "Nautilus", "image" => "Nautilus.png"},
    "119" => {"name" => "Draven", "image" => "Draven.png"},
    "432" => {"name" => "Bard", "image" => "Bard.png"},
    "245" => {"name" => "Ekko", "image" => "Ekko.png"},
    "82" => {"name" => "Mordekaiser", "image" => "Mordekaiser.png"},
    "83" => {"name" => "Yorick", "image" => "Yorick.png"},
    "80" => {"name" => "Pantheon", "image" => "Pantheon.png"},
    "81" => {"name" => "Ezreal", "image" => "Ezreal.png"},
    "86" => {"name" => "Garen", "image" => "Garen.png"},
    "84" => {"name" => "Akali", "image" => "Akali.png"},
    "85" => {"name" => "Kennen", "image" => "Kennen.png"},
    "67" => {"name" => "Vayne", "image" => "Vayne.png"},
    "126" => {"name" => "Jayce", "image" => "Jayce.png"},
    "69" => {"name" => "Cassiopeia", "image" => "Cassiopeia.png"},
    "127" => {"name" => "Lissandra", "image" => "Lissandra.png"},
    "68" => {"name" => "Rumble", "image" => "Rumble.png"},
    "121" => {"name" => "Kha'Zix", "image" => "Khazix.png"},
    "122" => {"name" => "Darius", "image" => "Darius.png"},
    "120" => {"name" => "Hecarim", "image" => "Hecarim.png"},
    "72" => {"name" => "Skarner", "image" => "Skarner.png"},
    "236" => {"name" => "Lucian", "image" => "Lucian.png"},
    "74" => {"name" => "Heimerdinger", "image" => "Heimerdinger.png"},
    "75" => {"name" => "Nasus", "image" => "Nasus.png"},
    "238" => {"name" => "Zed", "image" => "Zed.png"},
    "76" => {"name" => "Nidalee", "image" => "Nidalee.png"},
    "134" => {"name" => "Syndra", "image" => "Syndra.png"},
    "133" => {"name" => "Quinn", "image" => "Quinn.png"},
    "59" => {"name" => "Jarvan IV", "image" => "JarvanIV.png"},
    "58" => {"name" => "Renekton", "image" => "Renekton.png"},
    "57" => {"name" => "Maokai", "image" => "Maokai.png"},
    "56" => {"name" => "Nocturne", "image" => "Nocturne.png"},
    "55" => {"name" => "Katarina", "image" => "Katarina.png"},
    "64" => {"name" => "Lee Sin", "image" => "LeeSin.png"},
    "62" => {"name" => "Wukong", "image" => "MonkeyKing.png"},
    "63" => {"name" => "Brand", "image" => "Brand.png"},
    "268" => {"name" => "Azir", "image" => "Azir.png"},
    "267" => {"name" => "Nami", "image" => "Nami.png"},
    "60" => {"name" => "Elise", "image" => "Elise.png"},
    "131" => {"name" => "Diana", "image" => "Diana.png"},
    "61" => {"name" => "Orianna", "image" => "Orianna.png"},
    "266" => {"name" => "Aatrox", "image" => "Aatrox.png"},
    "143" => {"name" => "Zyra", "image" => "Zyra.png"},
    "48" => {"name" => "Trundle", "image" => "Trundle.png"},
    "45" => {"name" => "Veigar", "image" => "Veigar.png"},
    "44" => {"name" => "Taric", "image" => "Taric.png"},
    "51" => {"name" => "Caitlyn", "image" => "Caitlyn.png"},
    "53" => {"name" => "Blitzcrank", "image" => "Blitzcrank.png"},
    "54" => {"name" => "Malphite", "image" => "Malphite.png"},
    "254" => {"name" => "Vi", "image" => "Vi.png"},
    "50" => {"name" => "Swain", "image" => "Swain.png"}
  }

  module ClassMethods
    def champion_name_for_id(champion_id)
      CHAMPIONS[champion_id]["name"]
    end

    def champion_image_for_id(champion_id)
      CHAMPIONS[champion_id]["image"]
    end
  end
end
